### ISSUE TITLE
feature request: add .pyi interface file for IDEs.

### ISSUE THREAD

**Issue by Houston4444** [gesellkammer/pyliblo3#3]
Hi !

I was about to fork the original pyliblo seeing no news and no answers from the author and the incompatibility with python 3.11.
I saw this fork, so first, thank you, I won't have to do that.

On the original pyliblo, I made a PR https://github.com/dsacre/pyliblo/pull/27 with a .pyi interface file, its goal is just to make IDEs understanding liblo functions and methods (it helps auto-completion). The file is here: https://github.com/Houston4444/pyliblo/blob/add_interface/liblo/__init__.pyi .

Unfortunately, I did not understand how to install this file correctly with your fork, probably something stupid, but I figure you will know how to do it quickly.

I will ask tomy users and some distribution packagers  to distribute your fork and not the original one.

**Comment by gesellkammer** [comment]
Added
